// 더미 청년정책 데이터 — 온통청년 API(getYouthPolicyList) raw 응답 shape 그대로.
// UT용 저충실도 데이터이며 실제 값이 아니다. 실제 API 연동 시 이 배열을 BFF fetch로 교체.
//
// 케이스 커버리지 (판정/추천 UI 검증용):
//  · 명확한 해당       : #1 #5 #13
//  · 연령 비해당        : #8(19~24) #7(영농·연령↑)
//  · 지역 비해당        : #6(서울 한정) #9(경기 한정)
//  · 소득 비해당        : #11(차상위) #6
//  · 취업상태 조건       : #3 #9(재직자) #10(창업자) #2 #15(미취업자)
//  · 학력 조건          : #12(대학 재학)
//  · 조건부(자유텍스트)  : #2 #10 #14 #15
//  · ★ B-2 노이즈       : #4(경계선 지능 청년 — 일반 청년에겐 무관한데 "청년+복지"로 잡혀 노출)

import type { YouthPolicyRaw } from "@/lib/youth-policy/types";

export const dummyPoliciesRaw: readonly YouthPolicyRaw[] = [
  {
    plcyNo: "P0001",
    plcyNm: "청년 월세 특별지원",
    plcyKywdNm: "주거,월세,독립",
    plcyExplnCn: "무주택 청년의 월세 부담을 덜기 위해 월 최대 20만원을 최대 12개월 지원합니다.",
    lclsfNm: "주거",
    mclsfNm: "주거비 지원",
    plcySprtCn: "월 최대 20만원 × 최대 12개월",
    sprtSclCnt: "",
    sprvsnInstCdNm: "국토교통부",
    operInstCdNm: "각 지자체",
    aplyYmd: "20260101 ~ 20261231",
    plcyAplyMthdCn: "복지로 또는 주소지 행정복지센터 방문 신청",
    srngMthdCn: "소득·재산 요건 심사",
    sbmsnDcmntCn: "임대차계약서,월세이체 증빙,소득 증빙",
    aplyUrlAddr: "https://www.bokjiro.go.kr",
    refUrlAddr1: null,
    sprtTrgtMinAge: "19",
    sprtTrgtMaxAge: "34",
    sprtTrgtAgeLmtYn: "Y",
    earnCndSeCd: "0043002",
    earnMinAmt: "0",
    earnMaxAmt: "40000000",
    earnEtcCn: "",
    zipCd: "",
    jobCd: "0013010",
    schoolCd: "0049010",
    sBizCd: "0014010",
    addAplyQlfcCndCn: "",
  },
  {
    plcyNo: "P0002",
    plcyNm: "국민취업지원제도",
    plcyKywdNm: "취업,구직촉진수당,직업훈련",
    plcyExplnCn: "취업이 어려운 청년에게 취업지원 서비스와 구직촉진수당을 제공합니다.",
    lclsfNm: "일자리",
    mclsfNm: "취업 지원",
    plcySprtCn: "구직촉진수당 월 50~90만원(최대 6개월) + 취업지원 서비스",
    sprtSclCnt: "",
    sprvsnInstCdNm: "고용노동부",
    operInstCdNm: "고용센터",
    aplyYmd: "상시",
    plcyAplyMthdCn: "워크넷·고용24 온라인 또는 고용센터 방문",
    srngMthdCn: "소득·재산·취업경험에 따른 유형 판정",
    sbmsnDcmntCn: "신분증,소득·재산 증빙",
    aplyUrlAddr: "https://www.work24.go.kr",
    refUrlAddr1: null,
    sprtTrgtMinAge: "18",
    sprtTrgtMaxAge: "34",
    sprtTrgtAgeLmtYn: "Y",
    earnCndSeCd: "0043003",
    earnMinAmt: "",
    earnMaxAmt: "",
    earnEtcCn: "가구 중위소득 및 재산 요건에 따라 I유형/II유형 구분",
    zipCd: "",
    jobCd: "0013003",
    schoolCd: "0049010",
    sBizCd: "0014010",
    addAplyQlfcCndCn:
      "구직촉진수당(I유형)은 가구 중위소득 60% 이하 및 재산 4억원 이하, 최근 2년 내 취업경험 100일 이상 요건을 모두 충족해야 함",
  },
  {
    plcyNo: "P0003",
    plcyNm: "청년내일채움공제",
    plcyKywdNm: "자산형성,중소기업,재직",
    plcyExplnCn: "중소기업 재직 청년의 자산 형성을 돕는 공제 상품입니다.",
    lclsfNm: "일자리",
    mclsfNm: "자산 형성",
    plcySprtCn: "본인+기업+정부 적립으로 만기 시 목돈 마련",
    sprtSclCnt: "",
    sprvsnInstCdNm: "고용노동부",
    operInstCdNm: "운영기관",
    aplyYmd: "상시",
    plcyAplyMthdCn: "청년내일채움공제 누리집 온라인 신청",
    srngMthdCn: "고용보험 이력 확인",
    sbmsnDcmntCn: "재직 증빙,고용보험 가입 확인서",
    aplyUrlAddr: null,
    refUrlAddr1: null,
    sprtTrgtMinAge: "15",
    sprtTrgtMaxAge: "34",
    sprtTrgtAgeLmtYn: "Y",
    earnCndSeCd: "0043001",
    earnMinAmt: "",
    earnMaxAmt: "",
    earnEtcCn: "",
    zipCd: "",
    jobCd: "0013001",
    schoolCd: "0049010",
    sBizCd: "0014001",
    addAplyQlfcCndCn: "중소기업 정규직 취업 후 6개월 이내 가입",
  },
  {
    plcyNo: "P0004",
    plcyNm: "경계선 지능 청년 자립 지원",
    plcyKywdNm: "청년,복지,자립,느린학습자",
    plcyExplnCn: "경계선 지능(느린학습자) 청년의 사회 적응과 자립을 위한 맞춤 프로그램과 치료비를 지원합니다.",
    lclsfNm: "복지문화",
    mclsfNm: "복지 지원",
    plcySprtCn: "심리·인지 치료비 및 자립 프로그램 제공",
    sprtSclCnt: "200명",
    sprvsnInstCdNm: "보건복지부",
    operInstCdNm: "지역 복지관",
    aplyYmd: "20260301 ~ 20260430",
    plcyAplyMthdCn: "지역 복지관 방문 상담 후 신청",
    srngMthdCn: "전문기관 진단 및 심사",
    sbmsnDcmntCn: "진단서,소득 증빙",
    aplyUrlAddr: null,
    refUrlAddr1: null,
    sprtTrgtMinAge: "19",
    sprtTrgtMaxAge: "34",
    sprtTrgtAgeLmtYn: "Y",
    earnCndSeCd: "0043002",
    earnMinAmt: "0",
    earnMaxAmt: "30000000",
    earnEtcCn: "",
    zipCd: "",
    jobCd: "0013010",
    schoolCd: "0049010",
    sBizCd: "0014004",
    addAplyQlfcCndCn:
      "경계선 지능(지능지수 71~84) 진단을 받은 청년에 한함. 전문기관 진단서 필수",
  },
  {
    plcyNo: "P0005",
    plcyNm: "청년 마음건강 지원",
    plcyKywdNm: "심리상담,정신건강,복지",
    plcyExplnCn: "청년 누구나 전문 심리상담을 저렴하게 받을 수 있도록 상담 비용을 지원합니다.",
    lclsfNm: "복지문화",
    mclsfNm: "건강 지원",
    plcySprtCn: "전문 심리상담 최대 10회(회당 자기부담 소액)",
    sprtSclCnt: "",
    sprvsnInstCdNm: "보건복지부",
    operInstCdNm: "청년마음건강센터",
    aplyYmd: "20260101 ~ 20261130",
    plcyAplyMthdCn: "복지로 온라인 신청",
    srngMthdCn: "선착순",
    sbmsnDcmntCn: "신분증",
    aplyUrlAddr: "https://www.bokjiro.go.kr",
    refUrlAddr1: null,
    sprtTrgtMinAge: "19",
    sprtTrgtMaxAge: "34",
    sprtTrgtAgeLmtYn: "Y",
    earnCndSeCd: "0043001",
    earnMinAmt: "",
    earnMaxAmt: "",
    earnEtcCn: "",
    zipCd: "",
    jobCd: "0013010",
    schoolCd: "0049010",
    sBizCd: "0014010",
    addAplyQlfcCndCn: "",
  },
  {
    plcyNo: "P0006",
    plcyNm: "서울 청년수당",
    plcyKywdNm: "구직,활동비,서울",
    plcyExplnCn: "서울 거주 미취업 청년의 구직활동을 월 단위 활동지원금으로 돕습니다.",
    lclsfNm: "복지문화",
    mclsfNm: "생활 지원",
    plcySprtCn: "월 50만원 × 최대 6개월",
    sprtSclCnt: "20000명",
    sprvsnInstCdNm: "서울특별시",
    operInstCdNm: "서울시 청년활동지원센터",
    aplyYmd: "20260301 ~ 20260315",
    plcyAplyMthdCn: "청년몽땅정보통 온라인 신청",
    srngMthdCn: "소득 기준 및 무작위 추첨",
    sbmsnDcmntCn: "주민등록등본,소득 증빙",
    aplyUrlAddr: "https://youth.seoul.go.kr",
    refUrlAddr1: null,
    sprtTrgtMinAge: "19",
    sprtTrgtMaxAge: "34",
    sprtTrgtAgeLmtYn: "Y",
    earnCndSeCd: "0043003",
    earnMinAmt: "",
    earnMaxAmt: "",
    earnEtcCn: "가구 기준 중위소득 150% 이하 (1인 가구 세전 연 약 4,300만원)",
    zipCd: "서울특별시",
    jobCd: "0013003",
    schoolCd: "0049010",
    sBizCd: "0014010",
    addAplyQlfcCndCn: "졸업 후 2년 경과한 미취업자",
  },
  {
    plcyNo: "P0007",
    plcyNm: "농촌 청년 정착 지원금",
    plcyKywdNm: "귀농,영농,정착",
    plcyExplnCn: "농촌에 정착해 영농에 종사하는 청년에게 정착지원금을 지급합니다.",
    lclsfNm: "일자리",
    mclsfNm: "창업·정착",
    plcySprtCn: "월 최대 110만원 × 최대 3년",
    sprtSclCnt: "",
    sprvsnInstCdNm: "농림축산식품부",
    operInstCdNm: "지자체",
    aplyYmd: "20260201 ~ 20260331",
    plcyAplyMthdCn: "농림사업정보시스템(Agrix) 신청",
    srngMthdCn: "영농계획 평가",
    sbmsnDcmntCn: "영농계획서,농지 확보 증빙",
    aplyUrlAddr: null,
    refUrlAddr1: null,
    sprtTrgtMinAge: "18",
    sprtTrgtMaxAge: "45",
    sprtTrgtAgeLmtYn: "Y",
    earnCndSeCd: "0043001",
    earnMinAmt: "",
    earnMaxAmt: "",
    earnEtcCn: "",
    zipCd: "",
    jobCd: "0013008",
    schoolCd: "0049010",
    sBizCd: "0014003",
    addAplyQlfcCndCn: "독립경영 3년 이하의 청년 농업인",
  },
  {
    plcyNo: "P0008",
    plcyNm: "청년 문화예술패스",
    plcyKywdNm: "문화,공연,전시",
    plcyExplnCn: "만 19~24세 청년에게 공연·전시 관람비를 지원해 문화 향유를 돕습니다.",
    lclsfNm: "복지문화",
    mclsfNm: "문화 지원",
    plcySprtCn: "연 최대 15만원 문화이용권",
    sprtSclCnt: "160000명",
    sprvsnInstCdNm: "문화체육관광부",
    operInstCdNm: "한국문화예술위원회",
    aplyYmd: "20260101 ~ 20260630",
    plcyAplyMthdCn: "인터파크·예스24 등 제휴처 온라인 발급",
    srngMthdCn: "선착순",
    sbmsnDcmntCn: "신분증",
    aplyUrlAddr: null,
    refUrlAddr1: null,
    sprtTrgtMinAge: "19",
    sprtTrgtMaxAge: "24",
    sprtTrgtAgeLmtYn: "Y",
    earnCndSeCd: "0043001",
    earnMinAmt: "",
    earnMaxAmt: "",
    earnEtcCn: "",
    zipCd: "",
    jobCd: "0013010",
    schoolCd: "0049010",
    sBizCd: "0014010",
    addAplyQlfcCndCn: "",
  },
  {
    plcyNo: "P0009",
    plcyNm: "경기 중소기업 청년 교통비 지원",
    plcyKywdNm: "교통비,중소기업,경기",
    plcyExplnCn: "경기도 소재 중소기업에 재직 중인 청년의 대중교통비를 분기별로 지원합니다.",
    lclsfNm: "일자리",
    mclsfNm: "근로 지원",
    plcySprtCn: "분기 최대 15만원(연 60만원)",
    sprtSclCnt: "",
    sprvsnInstCdNm: "경기도",
    operInstCdNm: "경기도일자리재단",
    aplyYmd: "20260401 ~ 20260430",
    plcyAplyMthdCn: "잡아바 온라인 신청",
    srngMthdCn: "재직 확인",
    sbmsnDcmntCn: "재직증명서,교통비 사용 내역",
    aplyUrlAddr: null,
    refUrlAddr1: null,
    sprtTrgtMinAge: "18",
    sprtTrgtMaxAge: "34",
    sprtTrgtAgeLmtYn: "Y",
    earnCndSeCd: "0043001",
    earnMinAmt: "",
    earnMaxAmt: "",
    earnEtcCn: "",
    zipCd: "경기도",
    jobCd: "0013001",
    schoolCd: "0049010",
    sBizCd: "0014001",
    addAplyQlfcCndCn: "",
  },
  {
    plcyNo: "P0010",
    plcyNm: "청년 창업 사업화 지원",
    plcyKywdNm: "창업,사업화,스타트업",
    plcyExplnCn: "예비·초기 청년 창업자에게 사업화 자금과 멘토링을 제공합니다.",
    lclsfNm: "일자리",
    mclsfNm: "창업 지원",
    plcySprtCn: "사업화 자금 최대 5천만원 + 멘토링",
    sprtSclCnt: "500팀",
    sprvsnInstCdNm: "중소벤처기업부",
    operInstCdNm: "창업진흥원",
    aplyYmd: "20260215 ~ 20260315",
    plcyAplyMthdCn: "K-스타트업 온라인 신청",
    srngMthdCn: "서류·발표 평가",
    sbmsnDcmntCn: "사업계획서",
    aplyUrlAddr: "https://www.k-startup.go.kr",
    refUrlAddr1: null,
    sprtTrgtMinAge: "19",
    sprtTrgtMaxAge: "39",
    sprtTrgtAgeLmtYn: "Y",
    earnCndSeCd: "0043001",
    earnMinAmt: "",
    earnMaxAmt: "",
    earnEtcCn: "",
    zipCd: "",
    jobCd: "0013006",
    schoolCd: "0049010",
    sBizCd: "0014010",
    addAplyQlfcCndCn: "예비창업자 또는 창업 3년 이내 기업 대표",
  },
  {
    plcyNo: "P0011",
    plcyNm: "청년 저축계좌",
    plcyKywdNm: "자산형성,저소득,저축",
    plcyExplnCn: "일하는 저소득 청년의 자산 형성을 위해 저축액에 정부가 매칭 적립합니다.",
    lclsfNm: "복지문화",
    mclsfNm: "자산 형성",
    plcySprtCn: "본인 저축 월 10만원 + 정부 매칭 30만원",
    sprtSclCnt: "",
    sprvsnInstCdNm: "보건복지부",
    operInstCdNm: "지자체",
    aplyYmd: "20260501 ~ 20260520",
    plcyAplyMthdCn: "행정복지센터 방문 신청",
    srngMthdCn: "소득·근로 요건 심사",
    sbmsnDcmntCn: "소득 증빙,재직 증빙",
    aplyUrlAddr: null,
    refUrlAddr1: null,
    sprtTrgtMinAge: "15",
    sprtTrgtMaxAge: "39",
    sprtTrgtAgeLmtYn: "Y",
    earnCndSeCd: "0043003",
    earnMinAmt: "",
    earnMaxAmt: "",
    earnEtcCn: "근로·사업소득 있는 차상위계층 이하 (기준 중위소득 50% 수준)",
    zipCd: "",
    jobCd: "0013001",
    schoolCd: "0049010",
    sBizCd: "0014005",
    addAplyQlfcCndCn: "근로·사업 소득이 있는 차상위 이하 가구의 청년",
  },
  {
    plcyNo: "P0012",
    plcyNm: "대학생 학자금 대출이자 지원",
    plcyKywdNm: "학자금,대출이자,대학생",
    plcyExplnCn: "대학 재학 중인 청년의 학자금 대출이자를 지원해 학업 부담을 낮춥니다.",
    lclsfNm: "교육",
    mclsfNm: "학자금 지원",
    plcySprtCn: "재학 기간 중 학자금 대출이자 전액",
    sprtSclCnt: "",
    sprvsnInstCdNm: "교육부",
    operInstCdNm: "한국장학재단",
    aplyYmd: "20260301 ~ 20260430",
    plcyAplyMthdCn: "한국장학재단 온라인 신청",
    srngMthdCn: "재학·대출 확인",
    sbmsnDcmntCn: "재학증명서,대출 내역",
    aplyUrlAddr: "https://www.kosaf.go.kr",
    refUrlAddr1: null,
    sprtTrgtMinAge: "19",
    sprtTrgtMaxAge: "29",
    sprtTrgtAgeLmtYn: "Y",
    earnCndSeCd: "0043001",
    earnMinAmt: "",
    earnMaxAmt: "",
    earnEtcCn: "",
    zipCd: "",
    jobCd: "0013010",
    schoolCd: "0049004",
    sBizCd: "0014010",
    addAplyQlfcCndCn: "",
  },
  {
    plcyNo: "P0013",
    plcyNm: "청년 전세보증금 반환보증 보증료 지원",
    plcyKywdNm: "전세,보증금,보증료",
    plcyExplnCn: "전세사기 예방을 위해 청년이 가입한 반환보증의 보증료를 지원합니다.",
    lclsfNm: "주거",
    mclsfNm: "주거 안전",
    plcySprtCn: "보증료 전액(최대 30만원)",
    sprtSclCnt: "",
    sprvsnInstCdNm: "국토교통부",
    operInstCdNm: "지자체",
    aplyYmd: "상시",
    plcyAplyMthdCn: "정부24 또는 관할 지자체 신청",
    srngMthdCn: "보증 가입 확인",
    sbmsnDcmntCn: "보증서,보증료 납부 증빙",
    aplyUrlAddr: "https://www.gov.kr",
    refUrlAddr1: null,
    sprtTrgtMinAge: "19",
    sprtTrgtMaxAge: "34",
    sprtTrgtAgeLmtYn: "Y",
    earnCndSeCd: "0043002",
    earnMinAmt: "0",
    earnMaxAmt: "50000000",
    earnEtcCn: "",
    zipCd: "",
    jobCd: "0013010",
    schoolCd: "0049010",
    sBizCd: "0014010",
    addAplyQlfcCndCn: "",
  },
  {
    plcyNo: "P0014",
    plcyNm: "여성 청년 경력단절 예방 지원",
    plcyKywdNm: "여성,경력단절,직업훈련",
    plcyExplnCn: "경력단절을 겪었거나 예정인 여성 청년에게 직업훈련과 재취업을 지원합니다.",
    lclsfNm: "일자리",
    mclsfNm: "취업 지원",
    plcySprtCn: "직업훈련비 + 재취업 장려금",
    sprtSclCnt: "",
    sprvsnInstCdNm: "여성가족부",
    operInstCdNm: "여성새로일하기센터",
    aplyYmd: "상시",
    plcyAplyMthdCn: "새일센터 방문 상담 후 신청",
    srngMthdCn: "상담 및 요건 확인",
    sbmsnDcmntCn: "신분증,경력 증빙",
    aplyUrlAddr: null,
    refUrlAddr1: null,
    sprtTrgtMinAge: "19",
    sprtTrgtMaxAge: "39",
    sprtTrgtAgeLmtYn: "Y",
    earnCndSeCd: "0043001",
    earnMinAmt: "",
    earnMaxAmt: "",
    earnEtcCn: "",
    zipCd: "",
    jobCd: "0013003",
    schoolCd: "0049010",
    sBizCd: "0014002",
    addAplyQlfcCndCn: "경력단절 여성 또는 경력단절 예정자",
  },
  {
    plcyNo: "P0015",
    plcyNm: "청년 해외취업 지원(K-Move)",
    plcyKywdNm: "해외취업,연수,글로벌",
    plcyExplnCn: "해외 취업을 희망하는 청년에게 맞춤형 연수와 취업 알선을 제공합니다.",
    lclsfNm: "일자리",
    mclsfNm: "취업 지원",
    plcySprtCn: "해외취업 연수 과정 + 항공·정착 일부 지원",
    sprtSclCnt: "",
    sprvsnInstCdNm: "고용노동부",
    operInstCdNm: "한국산업인력공단",
    aplyYmd: "20260110 ~ 20260210",
    plcyAplyMthdCn: "월드잡플러스 온라인 신청",
    srngMthdCn: "서류·면접 평가",
    sbmsnDcmntCn: "이력서,어학성적표(해당자)",
    aplyUrlAddr: "https://www.worldjob.or.kr",
    refUrlAddr1: null,
    sprtTrgtMinAge: "18",
    sprtTrgtMaxAge: "34",
    sprtTrgtAgeLmtYn: "Y",
    earnCndSeCd: "0043001",
    earnMinAmt: "",
    earnMaxAmt: "",
    earnEtcCn: "",
    zipCd: "",
    jobCd: "0013003",
    schoolCd: "0049010",
    sBizCd: "0014010",
    addAplyQlfcCndCn: "과정별 어학성적 기준 충족자 우대(일부 과정 필수)",
  },
];
